services:
  - type: static
    name: make-my-trip-frontend
    env: static
    static:
      buildCommand: npm run build
      publishPath: build
      routes:
        - src: /
          dest: /index.html
        - src: /.*
          dest: /index.html
